/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9ff",
        "tertiary-container": "#006e4b",
        "secondary-container": "#dae2fd",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "surface-variant": "#d3e4fe",
        "surface-container": "#e5eeff",
        "background": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#c3c0ff",
        "on-surface-variant": "#464555",
        "on-secondary-container": "#5c647a",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-surface": "#213145",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-primary": "#c3c0ff",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-container": "#67f4b7",
        "outline": "#777587",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "primary-container": "#4f46e5",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#cbdbf5",
        "secondary": "#565e74",
        "surface-container-high": "#dce9ff",
        "tertiary": "#005338",
        "primary-fixed": "#e2dfff",
        "on-secondary-fixed": "#131b2e",
        "primary": "#3525cd",
        "outline-variant": "#c7c4d8",
        "secondary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed": "#002113",
        "tertiary-fixed-dim": "#4edea3",
        "surface": "#f8f9ff",
        "on-primary-fixed": "#0f0069",
        "surface-tint": "#4d44e3",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary-container": "#dad7ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-lg": "1.25rem",
        "gutter": "1.25rem",
        "space-xl": "1.75rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "margin": "1.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-sm": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
