import os
import re

PAGES_DIR = r"T:\My Projects\Agentic AI Hackathon\Edupath\frontend\src\pages\generated"

for file in os.listdir(PAGES_DIR):
    if not file.endswith(".tsx"):
        continue
    filepath = os.path.join(PAGES_DIR, file)
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Fix common unclosed tags or syntax issues:
    # 1. <style>...</style> -> these should be removed or converted. We don't need inline style tags because we have Tailwind config globally.
    content = re.sub(r'<style>.*?</style>', '', content, flags=re.DOTALL)
    
    # 2. Fix { and } in text. (Only outside of JSX tags/attributes, which is hard with regex, but let's try a simple approach)
    # Actually, the most common issue is inline JS in html or raw braces in text.
    # We can just run a quick replace for known bad style outputs from our previous script.
    
    # Let's fix the inline styles generated by the previous script that might be malformed.
    # For example, style={{ width: 90% }} which is invalid, should be style={{ width: '90%' }}
    # But wait, the previous script generated: k + ": '" + v + "'"
    # Let's see what went wrong.
    
    # Just fix <main> not being closed if it wasn't.
    if "<main" in content and "</main>" not in content:
        content += "</main>"
    if "<div" in content:
         # simple heuristic, if EOF is reached and divs are unbalanced, just append </div>
         open_divs = content.count("<div")
         close_divs = content.count("</div")
         if open_divs > close_divs:
             content += "</div>" * (open_divs - close_divs)

    # Let's write it back. We will rely on Prettier/ESLint or manual fixes for the rest if it's small.
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

print("Ran basic JSX fixes.")
