"""Phase 9 Mentorship and Assistant

Revision ID: 0ec710acac47
Revises: e624741dfa63
Create Date: 2026-09-20 07:19:11.960884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec710acac47'
down_revision: Union[str, Sequence[str], None] = 'e624741dfa63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_conversations_id'), 'assistant_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_assistant_conversations_learner_id'), 'assistant_conversations', ['learner_id'], unique=False)
    op.create_table('active_mentorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['mentorship_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_mentorships_id'), 'active_mentorships', ['id'], unique=False)
    op.create_index(op.f('ix_active_mentorships_learner_id'), 'active_mentorships', ['learner_id'], unique=False)
    op.create_index(op.f('ix_active_mentorships_mentor_id'), 'active_mentorships', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_active_mentorships_request_id'), 'active_mentorships', ['request_id'], unique=True)
    op.create_table('assistant_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('response_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_messages_conversation_id'), 'assistant_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_assistant_messages_id'), 'assistant_messages', ['id'], unique=False)
    op.create_table('mentor_guidance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentorship_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_skill_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mentorship_id'], ['active_mentorships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_guidance_id'), 'mentor_guidance', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_guidance_mentorship_id'), 'mentor_guidance', ['mentorship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentor_guidance_mentorship_id'), table_name='mentor_guidance')
    op.drop_index(op.f('ix_mentor_guidance_id'), table_name='mentor_guidance')
    op.drop_table('mentor_guidance')
    op.drop_index(op.f('ix_assistant_messages_id'), table_name='assistant_messages')
    op.drop_index(op.f('ix_assistant_messages_conversation_id'), table_name='assistant_messages')
    op.drop_table('assistant_messages')
    op.drop_index(op.f('ix_active_mentorships_request_id'), table_name='active_mentorships')
    op.drop_index(op.f('ix_active_mentorships_mentor_id'), table_name='active_mentorships')
    op.drop_index(op.f('ix_active_mentorships_learner_id'), table_name='active_mentorships')
    op.drop_index(op.f('ix_active_mentorships_id'), table_name='active_mentorships')
    op.drop_table('active_mentorships')
    op.drop_index(op.f('ix_assistant_conversations_learner_id'), table_name='assistant_conversations')
    op.drop_index(op.f('ix_assistant_conversations_id'), table_name='assistant_conversations')
    op.drop_table('assistant_conversations')
    # ### end Alembic commands ###
