"""Add LearningObjective and WeeklyPlan

Revision ID: 3e0dc15c626c
Revises: 417c34faa2c6
Create Date: 2026-09-20 02:26:58.980379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0dc15c626c'
down_revision: Union[str, Sequence[str], None] = '417c34faa2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_gap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('estimated_effort_mins', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['skill_gap_id'], ['skill_gaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_objectives_id'), 'learning_objectives', ['id'], unique=False)
    op.create_index(op.f('ix_learning_objectives_skill_gap_id'), 'learning_objectives', ['skill_gap_id'], unique=False)
    op.create_table('weekly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('focus_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plans_id'), 'weekly_plans', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_learning_path_id'), 'weekly_plans', ['learning_path_id'], unique=False)
    with op.batch_alter_table('learning_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_learning_activities_weekly_plans', 'weekly_plans', ['weekly_plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_learning_activities_weekly_plans', type_='foreignkey')
        batch_op.drop_column('weekly_plan_id')
    op.drop_index(op.f('ix_weekly_plans_learning_path_id'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index(op.f('ix_learning_objectives_skill_gap_id'), table_name='learning_objectives')
    op.drop_index(op.f('ix_learning_objectives_id'), table_name='learning_objectives')
    op.drop_table('learning_objectives')
    # ### end Alembic commands ###
