"""Add practice_task_id and assessment_id to LearningActivity

Revision ID: 95ca9a82161c
Revises: 3e0dc15c626c
Create Date: 2026-09-20 02:45:54.856161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ca9a82161c'
down_revision: Union[str, Sequence[str], None] = '3e0dc15c626c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice_task_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assessment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_learning_activities_assessments', 'assessments', ['assessment_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_learning_activities_practice_tasks', 'practice_tasks', ['practice_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_learning_activities_practice_tasks', type_='foreignkey')
        batch_op.drop_constraint('fk_learning_activities_assessments', type_='foreignkey')
        batch_op.drop_column('assessment_id')
        batch_op.drop_column('practice_task_id')
    # ### end Alembic commands ###
