"""add plan adaptation model

Revision ID: e624741dfa63
Revises: 95ca9a82161c
Create Date: 2026-09-20 03:05:39.741676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e624741dfa63'
down_revision: Union[str, Sequence[str], None] = '95ca9a82161c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_adaptations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=False),
    sa.Column('trigger_condition', sa.String(length=100), nullable=False),
    sa.Column('action_taken', sa.String(length=100), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_adaptations_id'), 'plan_adaptations', ['id'], unique=False)
    op.create_index(op.f('ix_plan_adaptations_learner_id'), 'plan_adaptations', ['learner_id'], unique=False)
    op.create_index(op.f('ix_plan_adaptations_learning_path_id'), 'plan_adaptations', ['learning_path_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_adaptations_learning_path_id'), table_name='plan_adaptations')
    op.drop_index(op.f('ix_plan_adaptations_learner_id'), table_name='plan_adaptations')
    op.drop_index(op.f('ix_plan_adaptations_id'), table_name='plan_adaptations')
    op.drop_table('plan_adaptations')
    # ### end Alembic commands ###
